### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ghost** [rikurauhala/yesan#1]
(In English, because the documentation was in English)

Downloaded 2022-05-03 19:00

# General points

- You've separated minor things into modules nicely (messages, colors, styles, fonts etc.), this helps keep everything consistent and helps maintenance
- Generally good separation of UI, Logic and Data storage
- Both the auto-formatter and Pylint have suggestions in places, you should consider implementing these
- The code is very clean and readable, good work!

### UI - General
UI code with TKinter can get very messy, but you've done an excellent job of keeping things organized and clear with functions!

### AccountView
Calculation of net worth seems to take place in the UI code. I see why you did it this way, but consider putting it somewhere else.

### TransactionService
`_convert_to_int()` could be fine, if the data was know to be in the correct format (as is the case in `format_amount()`). Right now the user can input anything and the function will blindly try to convert it to an int, which can raise exceptions. A simple regex match at the start of the function and handling that situation appropriately OR having a separate validation function that the UI can call would solve this.

# Unrelated to code (ie. usability)
The ability to delete accounts and transactions would be great.

**Comment by rikurauhala** [comment]
Kiitos hyvästä palautteesta! Thank you for the feedback.
